import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { Star, Puzzle, Brain, Zap, Trophy } from "lucide-react";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const floatingIcons = [
  {
    id: 1,
    icon: Star,
    left: "10%",
    top: "15%",
    size: "1.2rem",
    duration: "15s",
    opacity: 0.3,
    delay: "0s",
  },
  {
    id: 2,
    icon: Puzzle,
    left: "85%",
    top: "25%",
    size: "1.5rem",
    duration: "18s",
    opacity: 0.2,
    delay: "1s",
  },
  {
    id: 3,
    icon: Brain,
    left: "20%",
    top: "75%",
    size: "1.8rem",
    duration: "20s",
    opacity: 0.3,
    delay: "2s",
  },
  {
    id: 4,
    icon: Zap,
    left: "75%",
    top: "80%",
    size: "1rem",
    duration: "12s",
    opacity: 0.2,
    delay: "3s",
  },
  {
    id: 5,
    icon: Trophy,
    left: "30%",
    top: "10%",
    size: "1.4rem",
    duration: "17s",
    opacity: 0.25,
    delay: "1.5s",
  },
  {
    id: 6,
    icon: Star,
    left: "60%",
    top: "65%",
    size: "1.3rem",
    duration: "19s",
    opacity: 0.15,
    delay: "2.5s",
  },
  {
    id: 7,
    icon: Puzzle,
    left: "15%",
    top: "45%",
    size: "1.6rem",
    duration: "16s",
    opacity: 0.2,
    delay: "0.5s",
  },
  {
    id: 8,
    icon: Brain,
    left: "80%",
    top: "40%",
    size: "1.1rem",
    duration: "14s",
    opacity: 0.3,
    delay: "3.5s",
  },
  {
    id: 9,
    icon: Zap,
    left: "40%",
    top: "85%",
    size: "1.7rem",
    duration: "21s",
    opacity: 0.25,
    delay: "1.2s",
  },
  {
    id: 10,
    icon: Trophy,
    left: "65%",
    top: "15%",
    size: "1.5rem",
    duration: "13s",
    opacity: 0.2,
    delay: "2.8s",
  },
  {
    id: 11,
    icon: Star,
    left: "25%",
    top: "30%",
    size: "1.2rem",
    duration: "18s",
    opacity: 0.15,
    delay: "0.8s",
  },
  {
    id: 12,
    icon: Puzzle,
    left: "70%",
    top: "60%",
    size: "1.4rem",
    duration: "15s",
    opacity: 0.25,
    delay: "3.2s",
  },
  {
    id: 13,
    icon: Brain,
    left: "50%",
    top: "20%",
    size: "1.3rem",
    duration: "17s",
    opacity: 0.2,
    delay: "1.7s",
  },
  {
    id: 14,
    icon: Zap,
    left: "35%",
    top: "70%",
    size: "1.6rem",
    duration: "19s",
    opacity: 0.3,
    delay: "2.2s",
  },
  {
    id: 15,
    icon: Trophy,
    left: "90%",
    top: "55%",
    size: "1.1rem",
    duration: "16s",
    opacity: 0.25,
    delay: "0.3s",
  },
];
